version: '3'
services:
  app:
    # build: build
    image: peccu/emacs-wslg:latest
    container_name: emacs-wslg
    environment:
      # X11
      - DISPLAY
      # Wayland
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
      # PulseAudio
      - PULSE_SERVER
    volumes:
      - ~:/root
      # - /clip:/clip
      # X11
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Wayland and PulseAudio
      - /mnt/wslg:/mnt/wslg
      # vGPU
      - /dev/dxg:/dev/dxg
      - /usr/lib/wsl:/usr/lib/wsl
    restart: always
