version: '3'
services:
  app:
    # build: build
    image: peccu/wslg-emacs:latest
    environment:
      # X11
      - DISPLAY
      # Wayland
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
      # PulseAudio
      - PULSE_SERVER
    volumes:
      # - ~:/root
      - /clip:/clip
      # X11
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Wayland and PulseAudio
      - /mnt/wslg:/mnt/wslg
      # vGPU
      - /dev/dxg:/dev/dxg
      - /usr/lib/wsl:/usr/lib/wsl
    restart: always

# docker-compose up -d
# docker exec -it emacs-wslg-app-1 /usr/local/bin/emacs
# docker-compose exec app /usr/local/bin/emacs

# or without docker-compose
# docker build . -t peccu/wslg-emacs:latest
# docker run \
#        --rm \
#        --name emacs \
#        -d \
#        -v ~:/root \
#        -v /clip:/clip \
#        -v /tmp/.X11-unix:/tmp/.X11-unix \
#        -v /mnt/wslg:/mnt/wslg \
#        -e DISPLAY \
#        -e WAYLAND_DISPLAY \
#        -e XDG_RUNTIME_DIR \
#        -e PULSE_SERVER \
#        --entrypoint "/usr/bin/sleep infinity" \
#        peccu/wslg-emacs:latest
# docker exec -it emacs emacs

