name: Build Docker image (all branch)

on:
  push:
    branches:
      - buildenv
  release:
    types: [published]

jobs:
  build_images:
    name: Build Docker image for testing
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build Docker images for centos
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: cent
          push: false
