name: Build Docker image (all branch)

on:
  push:
    branches:
  release:
    types: [published]

jobs:
  build_images:
    name: Build Docker image for testing
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}

      - name: Build Docker images
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: build
          push: false
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:latest
          labels: ${{ steps.meta.outputs.labels }}
